language: node_js

node_js: stable

cache: yarn

before_install: yarn global add greenkeeper-lockfile

before_script: greenkeeper-lockfile-update

script:
  - yarn lint
  - yarn build

after_script: greenkeeper-lockfile-upload
