export const API_PREFIX = '/api'
export const ACCEPT_LANGUAGE = 'Accept-Language'
export const CAPTCHA_SESSION = 'CAPTCHA_SESSION'
export const VERIFICATION_CODE_COOKIE = 'VERIFICATION_CODE_COOKIE'
export const ENCRYPT_SECRET = 'rubick'
export const TOKEN = 'token'
